### ISSUE TITLE
Rebrand Roadmap

### ISSUE THREAD

**Issue by gib** [aptible/www.aptible.com#242]
# Rebrand

Table of Contents:
- [x] Sitemap
- [ ] Information Architecture
- [ ] Responsive
- [ ] Search
- [x] UI Kit
- [ ] Design Needs

## SiteMap
[Complete sitemap in drive](https://docs.google.com/document/d/1UQGMud1XSDehq4gtn4OAwwoN5tNsi6pVas6jMK4iplo/edit) lists sections 
Check list for each page. Will start with placeholders and have a separate checklist item 

**Bold** items need some work to create a basic layout / placeholder or need attention

- [x] Sitemap navigable, placeholders in place where work is in progress

- [x] /
  - [x] /enclave (technology)
  - [x] **/gridiron** (compliance)
  - [x] **/pricing**
  - [x] **/partners**
  - [x] **/customers** (child pages need content)
    - ~~[ ] /cto~~
    - ~~[ ] /ceo~~
    - ~~[ ] /security_professional~~
      - ~~[ ] /in-house~~
      - ~~[ ] /consultancy~~
    - ~~[ ] /compliance_professional~~
    - ~~[ ] /in-house~~
    - ~~[ ] /consultancy~~
    - ~~[ ] /dev_shop~~
    - [x] case studies
  - ~~[x] /resources~~
    - ~~[x] /$category (compliance)~~
      - ~~[ ] /$slug (aptible-vs-aws)~~
  - [x] /blog
    - [x] /$slug (post)
    - [x] /$author
    - ~~[ ] /$tag / $category (not on existing site, waiting to add these)~~
  - [x] /support
    - [x] /toolbelt
    - [x] /topics 
      - ~~[ ] /$category (tag individual docs for Enclave / Gridiron)~~
      - [x] /$slug
    - [x] /quickstart
      - [x] /$language
        - [x] /$framework
    - [x] **/status** (link to http://status.aptible.com/ ?)
  - [x] /company (index is about / team / careers) 
    - [x] /media
    - [x] /legal

## Information Architecture
Ability to navigate the contents of the site. Includes working navigation and middleman/framework related items
- [x] Investigate `middleman-blog` gem -- Requires an upgrade to Middleman 4 which deprecates two core features we use to build our dynamic support site content
    - See https://github.com/gib/www.aptible.com/tree/failed-middleman-blog
    - Upgrading to Middleman 4 - https://middlemanapp.com/basics/upgrade-v4/
- [x] Blog content needs middleman config for `$category` and each post given categories
- [x] Identify broken links to content (PDFs, images, etc)
- [x] Blog (@fancyremarker will dasherize underscores in titles) 
- [ ] Add Disqus to blog, quickstart, & topics

## Responsive
- [x] Main Navigation
- [ ] home header

## Search
Search / Swiftype related tasks
- [x] Working search in support header (small input)
- [x] Working search in support header (large input on index)
- [x] Working search page (currently /support/search)
- [ ] Categorize a global search index (joining support / www?) See https://swiftype.com/documentation/meta_tags2)

## UI Kit
Documentation and examples of components to build pages with. Track missing components / enumerate what should be available.
- [x] Colors
- [x] Buttons / Links
- [x] Navigation
- [x] Typography

Note: This is as complete as it will be until launch. I have some clean up planned to document many changes that the kit does not currently reflect.

## Content
- [x] Replace support topic sub titles (currently lorem) - use first paragraph with elipsis
- [x] Article list item arrow needs to be centered
- [ ] Enclave terminal - "carousel" terminal content changes with each step (from @fancyremarker)
- [x] Support Plans - Skip the VPN row, Skip bottom section
- [x] Pricing Calculator (later) (remove links, dev calc after initial release)
- [x] Resources Links: HIPAA, BAA, Y-Comb
- [ ] Enclave carousel content - for mobile, stack 'em
- [ ] Mobile, ditch terminal on enclave page
- [x] UCSF and Telepharm landing pages... quickest thing that works (consider grabbing all the static content, drop in a single page for each)
- [x] Remove all persona mentions (from /customers header)
- [x] Clean up Legal and FAQ (both share same layout, side section nav)
- [ ] Update product references in dashboard (see https://github.com/aptible/dashboard.aptible.com/issues/750)
- [x] ~~Getting Started~~ > Quickstart Guide(s)
- [x]  Swiftype Widget initialized on every turbolink load (see warning in console)
- [x] Stick side nav can end up in the header -- always update
- [x] logo grid 3up border
- [x] match heights of bordered cards (resource footer, quickstart icon links)

## Needs Design
- [ ] 404 Page

**Comment by gib** [comment]
Closing. Moved remaining items to individual issues. See development pipeline project: https://github.com/aptible/www.aptible.com/projects/1
